{
  parserClass="gauge.language.parser.SpecParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Spec"
  psiImplClassSuffix="Impl"
  psiPackage="gauge.language.psi"
  psiImplPackage="gauge.language.psi.impl"

  elementTypeHolderClass="gauge.language.psi.SpecTypes"
  elementTypeClass="gauge.language.psi.SpecElementType"
  tokenTypeClass="gauge.language.psi.SpecTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY